
tls:
  certificates:
    - certFile: /etc/traefik/certs/kosminen.org.pem
      keyFile: /etc/traefik/certs/kosminen.org-key.pem
      stores:
        - default
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/certs/kosminen.org.pem
        keyFile: /etc/traefik/certs/kosminen.org-key.pem
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true